hawkbit-compose: upgrade mysql:5.7 -> mariadb:10
latest hawkbit image no longer works with mysql 5.7:
org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Teams Edition or MySQL upgrade required: MySQL 5.7 is no longer supported by Flyway Community Edition, but still supported by Flyway Teams Edition.

Note that this requires a DB upgrade (even if we'd use a newer
mysql instead of mariadb)
The mariadb container has MARIADB_AUTO_UPGRADE which will
automatically run mariadb-upgrade, but that apparently fails from a
mysql:5.7 db, so the logical migration path would be mysqldump +
mysqlrestore... (we set it anyway for later minor upgrades)

Give it a try and let user deal with any failure if required.

Note for later: always do a mysqldump before upgrading containers?

Change-Id: I6fecda8abaa41f6029385d067e73b2bd9853d665